### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by prkHack** [krig/send_arp.py#3]
After doing some slight modifications to the code such that I get it to work, but I get this Error:

> Traceback (most recent call last):
>   File "send_arp.py", line 195, in <module>
>     main()
>   File "send_arp.py", line 177, in main
>     request_target_mac=bcast_mac)
>   File "send_arp.py", line 87, in send_arp
>     sock.bind((device, socket.SOCK_RAW))
>   File "C:\Anaconda2\lib\socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> socket.gaierror: [Errno 11001] getaddrinfo failed

Thank you very much in advance!

**Comment by krig** [comment]
Probably the name doesn't resolve correctly. try adding a `print name` before line 228 and see what is being passed in.

**Comment by prkHack** [comment]
Yeah I get 

> \

as the output.
