### ISSUE TITLE
socket.error: [Errno 19] No such device

### ISSUE THREAD

**Issue by MuntherN** [krig/send_arp.py#4]
Greeting ,

at first thank you very much for your great work , i am beginner in python , when i run your program i get the error below 

Traceback (most recent call last):
  File "send_arp.py", line 192, in <module>
    main()
  File "send_arp.py", line 174, in main
    request_target_mac=bcast_mac)
  File "send_arp.py", line 83, in send_arp
    sock.bind((device, socket.SOCK_RAW))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

i do not understand if i must write the src ip and src mac for sender device or destination device
best regards

**Comment by krig** [comment]
Hmm, it sounds like it is unable to figure out which network device to use. But it's impossible for me to determine what the problem is without knowing more details about your network configuration, the command line you used and what it is you are trying to do.

**Comment by MuntherN** [comment]
Thank for your reply .

i used ifconfig command to get the srcip, srcmac and brodcast ip and i write the command below : 

sudo python send_arp.py [-i 10] 10.0.2.15 08:00:27:c0:d6:60 10.0.2.255

Here all the log : 

ubuntu@sdnhubvm:~[02:41]$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:b0:67:cb:9c  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:c0:d6:60  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fec0:d660/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1180 (1.1 KB)  TX bytes:1332 (1.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1120 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1120 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:96544 (96.5 KB)  TX bytes:96544 (96.5 KB)


ubuntu@sdnhubvm:~/ryu/ryu/app/send_arp.py-master[03:00] (master)$ sudo python send_arp.py [-i 10] 10.0.2.15 08:00:27:c0:d6:60 10.0.2.255
Traceback (most recent call last):
  File "send_arp.py", line 192, in <module>
    main()
  File "send_arp.py", line 174, in main
    request_target_mac=bcast_mac)
  File "send_arp.py", line 83, in send_arp
    sock.bind((device, socket.SOCK_RAW))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device
ubuntu@sdnhubvm:~/ryu/ryu/app/send_arp.py-master[03:00] (master)$ 

Best Regards..

**Comment by Tianjiaojiao** [comment]
I have the similar problem.  Have you solved your problem? How to solve it?

**Comment by krig** [comment]
Well, the original problem was that the device argument was missing. The command takes at least four parameters.
